In [1]:
import pandas as pd
import re
import numpy as np
import torch
import random
from itables import show
import pubchempy as pcp
import rdkit
from rdkit import Chem
from rdkit.Chem import Descriptors
from descriptastorus.descriptors import rdDescriptors
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from functools import lru_cache

In [2]:
# Set random seed for reproducibility
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)

In [3]:
df=pd.read_csv('Cleaned_VLE_Data_with_Smiles_and_Mols.csv')

In [4]:
#To ensure mol are mol objects
df['mol1'] = df['Smiles 1'].apply(Chem.MolFromSmiles)
df['mol2'] = df['Smiles 2'].apply(Chem.MolFromSmiles)

[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors
[19:38:53] WARNING: not removing hydrogen atom without neighbors

In [5]:
df.head()

,property,value,phase,"Temperature, K","Pressure, kPa",Mole fraction,Component 1,Component 2,Smiles 1,Smiles 2,mol1,mol2
0,"Thermal conductivity, W/m/K",0.02096,Gas,300.0,724.0,0.2493,carbon dioxide,methane,C(=O)=O,C,<rdkit.Chem.rdchem.Mol object at 0x0000026C675...,<rdkit.Chem.rdchem.Mol object at 0x0000026C676...
1,"Thermal conductivity, W/m/K",0.02125,Gas,300.0,1288.0,0.2493,carbon dioxide,methane,C(=O)=O,C,<rdkit.Chem.rdchem.Mol object at 0x0000026C676...,<rdkit.Chem.rdchem.Mol object at 0x0000026C676...
2,"Thermal conductivity, W/m/K",0.02161,Gas,300.0,1835.0,0.2493,carbon dioxide,methane,C(=O)=O,C,<rdkit.Chem.rdchem.Mol object at 0x0000026C676...,<rdkit.Chem.rdchem.Mol object at 0x0000026C676...
3,"Thermal conductivity, W/m/K",0.02197,Gas,300.0,2335.0,0.2493,carbon dioxide,methane,C(=O)=O,C,<rdkit.Chem.rdchem.Mol object at 0x0000026C676...,<rdkit.Chem.rdchem.Mol object at 0x0000026C676...
4,"Thermal conductivity, W/m/K",0.02245,Gas,300.0,2820.0,0.2493,carbon dioxide,methane,C(=O)=O,C,<rdkit.Chem.rdchem.Mol object at 0x0000026C676...,<rdkit.Chem.rdchem.Mol object at 0x0000026C676...

In [6]:
from descriptastorus.descriptors import rdNormalizedDescriptors
generator = rdNormalizedDescriptors.RDKit2DNormalized()
print(generator.columns)

[('BalabanJ', <class 'numpy.float64'>), ('BertzCT', <class 'numpy.float64'>), ('Chi0', <class 'numpy.float64'>), ('Chi0n', <class 'numpy.float64'>), ('Chi0v', <class 'numpy.float64'>), ('Chi1', <class 'numpy.float64'>), ('Chi1n', <class 'numpy.float64'>), ('Chi1v', <class 'numpy.float64'>), ('Chi2n', <class 'numpy.float64'>), ('Chi2v', <class 'numpy.float64'>), ('Chi3n', <class 'numpy.float64'>), ('Chi3v', <class 'numpy.float64'>), ('Chi4n', <class 'numpy.float64'>), ('Chi4v', <class 'numpy.float64'>), ('EState_VSA1', <class 'numpy.float64'>), ('EState_VSA10', <class 'numpy.float64'>), ('EState_VSA11', <class 'numpy.float64'>), ('EState_VSA2', <class 'numpy.float64'>), ('EState_VSA3', <class 'numpy.float64'>), ('EState_VSA4', <class 'numpy.float64'>), ('EState_VSA5', <class 'numpy.float64'>), ('EState_VSA6', <class 'numpy.float64'>), ('EState_VSA7', <class 'numpy.float64'>), ('EState_VSA8', <class 'numpy.float64'>), ('EState_VSA9', <class 'numpy.float64'>), ('ExactMolWt', <class 'numpy.float64'>), ('FpDensityMorgan1', <class 'numpy.float64'>), ('FpDensityMorgan2', <class 'numpy.float64'>), ('FpDensityMorgan3', <class 'numpy.float64'>), ('FractionCSP3', <class 'numpy.float64'>), ('HallKierAlpha', <class 'numpy.float64'>), ('HeavyAtomCount', <class 'numpy.float64'>), ('HeavyAtomMolWt', <class 'numpy.float64'>), ('Ipc', <class 'numpy.float64'>), ('Kappa1', <class 'numpy.float64'>), ('Kappa2', <class 'numpy.float64'>), ('Kappa3', <class 'numpy.float64'>), ('LabuteASA', <class 'numpy.float64'>), ('MaxAbsEStateIndex', <class 'numpy.float64'>), ('MaxAbsPartialCharge', <class 'numpy.float64'>), ('MaxEStateIndex', <class 'numpy.float64'>), ('MaxPartialCharge', <class 'numpy.float64'>), ('MinAbsEStateIndex', <class 'numpy.float64'>), ('MinAbsPartialCharge', <class 'numpy.float64'>), ('MinEStateIndex', <class 'numpy.float64'>), ('MinPartialCharge', <class 'numpy.float64'>), ('MolLogP', <class 'numpy.float64'>), ('MolMR', <class 'numpy.float64'>), ('MolWt', <class 'numpy.float64'>), ('NHOHCount', <class 'numpy.float64'>), ('NOCount', <class 'numpy.float64'>), ('NumAliphaticCarbocycles', <class 'numpy.float64'>), ('NumAliphaticHeterocycles', <class 'numpy.float64'>), ('NumAliphaticRings', <class 'numpy.float64'>), ('NumAromaticCarbocycles', <class 'numpy.float64'>), ('NumAromaticHeterocycles', <class 'numpy.float64'>), ('NumAromaticRings', <class 'numpy.float64'>), ('NumHAcceptors', <class 'numpy.float64'>), ('NumHDonors', <class 'numpy.float64'>), ('NumHeteroatoms', <class 'numpy.float64'>), ('NumRadicalElectrons', <class 'numpy.float64'>), ('NumRotatableBonds', <class 'numpy.float64'>), ('NumSaturatedCarbocycles', <class 'numpy.float64'>), ('NumSaturatedHeterocycles', <class 'numpy.float64'>), ('NumSaturatedRings', <class 'numpy.float64'>), ('NumValenceElectrons', <class 'numpy.float64'>), ('PEOE_VSA1', <class 'numpy.float64'>), ('PEOE_VSA10', <class 'numpy.float64'>), ('PEOE_VSA11', <class 'numpy.float64'>), ('PEOE_VSA12', <class 'numpy.float64'>), ('PEOE_VSA13', <class 'numpy.float64'>), ('PEOE_VSA14', <class 'numpy.float64'>), ('PEOE_VSA2', <class 'numpy.float64'>), ('PEOE_VSA3', <class 'numpy.float64'>), ('PEOE_VSA4', <class 'numpy.float64'>), ('PEOE_VSA5', <class 'numpy.float64'>), ('PEOE_VSA6', <class 'numpy.float64'>), ('PEOE_VSA7', <class 'numpy.float64'>), ('PEOE_VSA8', <class 'numpy.float64'>), ('PEOE_VSA9', <class 'numpy.float64'>), ('RingCount', <class 'numpy.float64'>), ('SMR_VSA1', <class 'numpy.float64'>), ('SMR_VSA10', <class 'numpy.float64'>), ('SMR_VSA2', <class 'numpy.float64'>), ('SMR_VSA3', <class 'numpy.float64'>), ('SMR_VSA4', <class 'numpy.float64'>), ('SMR_VSA5', <class 'numpy.float64'>), ('SMR_VSA6', <class 'numpy.float64'>), ('SMR_VSA7', <class 'numpy.float64'>), ('SMR_VSA8', <class 'numpy.float64'>), ('SMR_VSA9', <class 'numpy.float64'>), ('SlogP_VSA1', <class 'numpy.float64'>), ('SlogP_VSA10', <class 'numpy.float64'>), ('SlogP_VSA11', <class 'numpy.float64'>), ('SlogP_VSA12', <class 'numpy.float64'>), ('SlogP_VSA2', <class 'numpy.float64'>), ('SlogP_VSA3', <class 'numpy.float64'>), ('SlogP_VSA4', <class 'numpy.float64'>), ('SlogP_VSA5', <class 'numpy.float64'>), ('SlogP_VSA6', <class 'numpy.float64'>), ('SlogP_VSA7', <class 'numpy.float64'>), ('SlogP_VSA8', <class 'numpy.float64'>), ('SlogP_VSA9', <class 'numpy.float64'>), ('TPSA', <class 'numpy.float64'>), ('VSA_EState1', <class 'numpy.float64'>), ('VSA_EState10', <class 'numpy.float64'>), ('VSA_EState2', <class 'numpy.float64'>), ('VSA_EState3', <class 'numpy.float64'>), ('VSA_EState4', <class 'numpy.float64'>), ('VSA_EState5', <class 'numpy.float64'>), ('VSA_EState6', <class 'numpy.float64'>), ('VSA_EState7', <class 'numpy.float64'>), ('VSA_EState8', <class 'numpy.float64'>), ('VSA_EState9', <class 'numpy.float64'>), ('fr_Al_COO', <class 'numpy.float64'>), ('fr_Al_OH', <class 'numpy.float64'>), ('fr_Al_OH_noTert', <class 'numpy.float64'>), ('fr_ArN', <class 'numpy.float64'>), ('fr_Ar_COO', <class 'numpy.float64'>), ('fr_Ar_N', <class 'numpy.float64'>), ('fr_Ar_NH', <class 'numpy.float64'>), ('fr_Ar_OH', <class 'numpy.float64'>), ('fr_COO', <class 'numpy.float64'>), ('fr_COO2', <class 'numpy.float64'>), ('fr_C_O', <class 'numpy.float64'>), ('fr_C_O_noCOO', <class 'numpy.float64'>), ('fr_C_S', <class 'numpy.float64'>), ('fr_HOCCN', <class 'numpy.float64'>), ('fr_Imine', <class 'numpy.float64'>), ('fr_NH0', <class 'numpy.float64'>), ('fr_NH1', <class 'numpy.float64'>), ('fr_NH2', <class 'numpy.float64'>), ('fr_N_O', <class 'numpy.float64'>), ('fr_Ndealkylation1', <class 'numpy.float64'>), ('fr_Ndealkylation2', <class 'numpy.float64'>), ('fr_Nhpyrrole', <class 'numpy.float64'>), ('fr_SH', <class 'numpy.float64'>), ('fr_aldehyde', <class 'numpy.float64'>), ('fr_alkyl_carbamate', <class 'numpy.float64'>), ('fr_alkyl_halide', <class 'numpy.float64'>), ('fr_allylic_oxid', <class 'numpy.float64'>), ('fr_amide', <class 'numpy.float64'>), ('fr_amidine', <class 'numpy.float64'>), ('fr_aniline', <class 'numpy.float64'>), ('fr_aryl_methyl', <class 'numpy.float64'>), ('fr_azide', <class 'numpy.float64'>), ('fr_azo', <class 'numpy.float64'>), ('fr_barbitur', <class 'numpy.float64'>), ('fr_benzene', <class 'numpy.float64'>), ('fr_benzodiazepine', <class 'numpy.float64'>), ('fr_bicyclic', <class 'numpy.float64'>), ('fr_diazo', <class 'numpy.float64'>), ('fr_dihydropyridine', <class 'numpy.float64'>), ('fr_epoxide', <class 'numpy.float64'>), ('fr_ester', <class 'numpy.float64'>), ('fr_ether', <class 'numpy.float64'>), ('fr_furan', <class 'numpy.float64'>), ('fr_guanido', <class 'numpy.float64'>), ('fr_halogen', <class 'numpy.float64'>), ('fr_hdrzine', <class 'numpy.float64'>), ('fr_hdrzone', <class 'numpy.float64'>), ('fr_imidazole', <class 'numpy.float64'>), ('fr_imide', <class 'numpy.float64'>), ('fr_isocyan', <class 'numpy.float64'>), ('fr_isothiocyan', <class 'numpy.float64'>), ('fr_ketone', <class 'numpy.float64'>), ('fr_ketone_Topliss', <class 'numpy.float64'>), ('fr_lactam', <class 'numpy.float64'>), ('fr_lactone', <class 'numpy.float64'>), ('fr_methoxy', <class 'numpy.float64'>), ('fr_morpholine', <class 'numpy.float64'>), ('fr_nitrile', <class 'numpy.float64'>), ('fr_nitro', <class 'numpy.float64'>), ('fr_nitro_arom', <class 'numpy.float64'>), ('fr_nitro_arom_nonortho', <class 'numpy.float64'>), ('fr_nitroso', <class 'numpy.float64'>), ('fr_oxazole', <class 'numpy.float64'>), ('fr_oxime', <class 'numpy.float64'>), ('fr_para_hydroxylation', <class 'numpy.float64'>), ('fr_phenol', <class 'numpy.float64'>), ('fr_phenol_noOrthoHbond', <class 'numpy.float64'>), ('fr_phos_acid', <class 'numpy.float64'>), ('fr_phos_ester', <class 'numpy.float64'>), ('fr_piperdine', <class 'numpy.float64'>), ('fr_piperzine', <class 'numpy.float64'>), ('fr_priamide', <class 'numpy.float64'>), ('fr_prisulfonamd', <class 'numpy.float64'>), ('fr_pyridine', <class 'numpy.float64'>), ('fr_quatN', <class 'numpy.float64'>), ('fr_sulfide', <class 'numpy.float64'>), ('fr_sulfonamd', <class 'numpy.float64'>), ('fr_sulfone', <class 'numpy.float64'>), ('fr_term_acetylene', <class 'numpy.float64'>), ('fr_tetrazole', <class 'numpy.float64'>), ('fr_thiazole', <class 'numpy.float64'>), ('fr_thiocyan', <class 'numpy.float64'>), ('fr_thiophene', <class 'numpy.float64'>), ('fr_unbrch_alkane', <class 'numpy.float64'>), ('fr_urea', <class 'numpy.float64'>), ('qed', <class 'numpy.float64'>)]

In [7]:
import tqdm.auto as tqdm
# 1. Define a wrapper function and apply the cache to IT
@lru_cache(maxsize=None)
def get_cached_descriptors(mol_input):
    # This function simply calls your generator
    # We hardcode 'None' here since you used it in your original snippet
    return generator.calculateMol(mol_input, None)

# 2. Now run your loops calling the CACHED function
# The first time a specific molecule is seen, it runs the generator.
# The second time (e.g., if the same molecule is in mol2), it returns instantly.

print("Processing Mol 1...")
x_1 = np.stack([get_cached_descriptors(m) for m in tqdm.tqdm(df['mol1'].tolist())])

print("Processing Mol 2...")
x_2 = np.stack([get_cached_descriptors(m) for m in tqdm.tqdm(df['mol2'].tolist())])

# Optional: Check cache stats to see how much time you saved
print(f"\nCache Info: {get_cached_descriptors.cache_info()}")

print(x_1.shape)
print(x_2.shape)

c:\Users\harry\anaconda3\envs\CHE1148\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Processing Mol 1...

 66%|██████▌   | 71470/108142 [28:13<11:34, 52.83it/s]  [20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71476/108142 [28:13<11:43, 52.15it/s][20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71482/108142 [28:13<11:43, 52.07it/s][20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:22] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71488/108142 [28:13<12:01, 50.77it/s][20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71494/108142 [28:13<12:26, 49.12it/s][20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71499/108142 [28:13<12:24, 49.23it/s][20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71504/108142 [28:13<12:21, 49.40it/s][20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71509/108142 [28:14<12:21, 49.42it/s][20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71514/108142 [28:14<12:50, 47.51it/s][20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71520/108142 [28:14<12:32, 48.67it/s][20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71526/108142 [28:14<12:16, 49.72it/s][20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71531/108142 [28:14<12:28, 48.89it/s][20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:23] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71537/108142 [28:14<12:12, 49.98it/s][20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71542/108142 [28:14<13:03, 46.72it/s][20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71548/108142 [28:14<12:32, 48.65it/s][20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71553/108142 [28:14<12:36, 48.39it/s][20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71559/108142 [28:15<12:28, 48.91it/s][20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71564/108142 [28:15<12:31, 48.70it/s][20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71570/108142 [28:15<12:23, 49.20it/s][20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71575/108142 [28:15<12:31, 48.69it/s][20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71581/108142 [28:15<12:21, 49.33it/s][20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:24] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71586/108142 [28:15<12:44, 47.79it/s][20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71591/108142 [28:15<13:11, 46.18it/s][20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71596/108142 [28:15<13:01, 46.76it/s][20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71601/108142 [28:15<12:56, 47.06it/s][20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71607/108142 [28:16<12:25, 48.98it/s][20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71612/108142 [28:16<12:26, 48.94it/s][20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71617/108142 [28:16<12:27, 48.84it/s][20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71623/108142 [28:16<12:10, 49.96it/s][20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71628/108142 [28:16<12:13, 49.76it/s][20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:25] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71633/108142 [28:16<13:03, 46.58it/s][20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71638/108142 [28:16<13:33, 44.86it/s][20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
 66%|██████▌   | 71644/108142 [28:16<12:57, 46.95it/s][20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71650/108142 [28:16<12:26, 48.88it/s][20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71656/108142 [28:17<12:17, 49.50it/s][20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71661/108142 [28:17<12:16, 49.55it/s][20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71666/108142 [28:17<12:18, 49.36it/s][20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71672/108142 [28:17<12:05, 50.24it/s][20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71678/108142 [28:17<11:58, 50.78it/s][20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:26] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71684/108142 [28:17<12:20, 49.24it/s][20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71689/108142 [28:17<12:31, 48.50it/s][20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71695/108142 [28:17<12:19, 49.31it/s][20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71701/108142 [28:17<12:06, 50.18it/s][20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71707/108142 [28:18<12:02, 50.41it/s][20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71713/108142 [28:18<12:12, 49.71it/s][20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71718/108142 [28:18<12:18, 49.31it/s][20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71723/108142 [28:18<12:21, 49.11it/s][20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:27] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71728/108142 [28:18<12:17, 49.35it/s][20:07:27] WARNING: not removing hydrogen atom without neighbors
[20:07:28] WARNING: not removing hydrogen atom without neighbors
[20:07:28] WARNING: not removing hydrogen atom without neighbors
[20:07:28] WARNING: not removing hydrogen atom without neighbors
[20:07:28] WARNING: not removing hydrogen atom without neighbors
 66%|██████▋   | 71733/108142 [28:18<12:20, 49.17it/s][20:07:28] WARNING: not removing hydrogen atom without neighbors
[20:07:28] WARNING: not removing hydrogen atom without neighbors
[20:07:28] WARNING: not removing hydrogen atom without neighbors
[20:07:28] WARNING: not removing hydrogen atom without neighbors
[20:07:28] WARNING: not removing hydrogen atom without neighbors

Processing Mol 2...

100%|██████████| 108142/108142 [35:40<00:00, 50.53it/s]

Cache Info: CacheInfo(hits=0, misses=216284, maxsize=None, currsize=216284)
(108142, 200)
(108142, 200)

In [8]:
np.save('descriptors_for_comp_1.npy', x_1)
np.save('descriptors_for_comp_2.npy', x_2)

In [9]:
df_mol1 = pd.DataFrame(x_1, columns=generator.columns)
df_mol2 = pd.DataFrame(x_2, columns=generator.columns)
df = pd.concat([df, df_mol1, df_mol2], axis=1)
print(df.shape)
df.head()

(108142, 412)

,property,value,phase,"Temperature, K","Pressure, kPa",Mole fraction,Component 1,Component 2,Smiles 1,Smiles 2,...,"(fr_sulfonamd, <class 'numpy.float64'>)","(fr_sulfone, <class 'numpy.float64'>)","(fr_term_acetylene, <class 'numpy.float64'>)","(fr_tetrazole, <class 'numpy.float64'>)","(fr_thiazole, <class 'numpy.float64'>)","(fr_thiocyan, <class 'numpy.float64'>)","(fr_thiophene, <class 'numpy.float64'>)","(fr_unbrch_alkane, <class 'numpy.float64'>)","(fr_urea, <class 'numpy.float64'>)","(qed, <class 'numpy.float64'>)"
0,"Thermal conductivity, W/m/K",0.02096,Gas,300.0,724.0,0.2493,carbon dioxide,methane,C(=O)=O,C,...,1.593061e-17,5.766101e-14,2.957989e-11,0.168378,0.16738,1.481515e-18,2.324150e-16,4.703598e-08,0.166633,0.187493
1,"Thermal conductivity, W/m/K",0.02125,Gas,300.0,1288.0,0.2493,carbon dioxide,methane,C(=O)=O,C,...,1.593061e-17,5.766101e-14,2.957989e-11,0.168378,0.16738,1.481515e-18,2.324150e-16,4.703598e-08,0.166633,0.187493
2,"Thermal conductivity, W/m/K",0.02161,Gas,300.0,1835.0,0.2493,carbon dioxide,methane,C(=O)=O,C,...,1.593061e-17,5.766101e-14,2.957989e-11,0.168378,0.16738,1.481515e-18,2.324150e-16,4.703598e-08,0.166633,0.187493
3,"Thermal conductivity, W/m/K",0.02197,Gas,300.0,2335.0,0.2493,carbon dioxide,methane,C(=O)=O,C,...,1.593061e-17,5.766101e-14,2.957989e-11,0.168378,0.16738,1.481515e-18,2.324150e-16,4.703598e-08,0.166633,0.187493
4,"Thermal conductivity, W/m/K",0.02245,Gas,300.0,2820.0,0.2493,carbon dioxide,methane,C(=O)=O,C,...,1.593061e-17,5.766101e-14,2.957989e-11,0.168378,0.16738,1.481515e-18,2.324150e-16,4.703598e-08,0.166633,0.187493

In [10]:
df.to_csv('Cleaned_VLE_Data_with_Smiles_and_Mols_and_Descriptors.csv')

In [18]:
df.dropna(inplace=True)
df.shape    
df.to_csv('Cleaned_VLE_Data_with_Smiles_and_Mols_and_Descriptors.csv')

In [19]:
print(df.shape)

(106383, 412)